- name: Wdrożenie wielu środowisk użytkowników
  hosts: localhost
  become: yes
  tasks:
    - name: Upewnij się, że Docker działa
      apt:
        name: docker.io
        state: present

    - name: Serwer dla Użytkownika 1
      community.docker.docker_container:
        name: user-one-app
        image: httpd:alpine
        ports:
          - "8083:80"
        state: started

    - name: Serwer dla Użytkownika 2
      community.docker.docker_container:
        name: user-two-app
        image: httpd:alpine
        ports:
          - "8084:80"
        state: started